#logging.level.org.springframework = DEBUG
management:
  security:
    enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: *
app:
  name: "NiazSampleSpring200"

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:h2_db;DB_CLOSE_DELAY=-1;
#    url: jdbc:h2:file:~/h2_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
